# fly.toml app configuration file generated for ffs-sportcardauctions-rewrite-laravel-2 on 2023-09-19T17:46:02-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ffs-sportcardauctions-rewrite-laravel-2"
primary_region = "dfw"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.2"

[env]
  APP_ENV = "production"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"
  DB_CONNECTION = "pgsql"
  QUEUE_CONNECTION="database"
  MAIL_MAILER = "smtp"
  MAIL_HOST = "sandbox.smtp.mailtrap.io"
  MAIL_PORT = 2525
  SSR_URL = "ssr.process.ffs-sportcardauctions-rewrite-laravel-2.internal:13714"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[deploy]
  release_command = "php /var/www/html/artisan migrate --force"

[processes]
  app=""
  worker="php artisan queue:listen"
  ssr="php /var/www/html/artisan inertia:start-ssr"
  cron = "cron -f"
